name: CI

on: [ pull_request ]

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-XX:+HeapDumpOnOutOfMemoryError -XX:MetaspaceSize=1g"

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        java-version: [ 11, 19 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup JDK 8
        if: matrix.os == 'macos-latest' || matrix.os == 'windows-latest'
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 8

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java-version }}

      - name: Check API Compatibility
        if: matrix.os == 'macos-latest' && matrix.java-version == 19
        run: >
          ./gradlew apiCheck --stacktrace

      - name: Run macOS Tests [ Java 11 ]
        if: matrix.os == 'macos-latest' && matrix.java-version == 11
        run: >
          ./gradlew check --stacktrace
          -PKMP_TARGETS="IOS_ARM64,IOS_X64,IOS_SIMULATOR_ARM64,JS,JVM,TVOS_ARM64,TVOS_X64,TVOS_SIMULATOR_ARM64,WASM_JS,WASM_WASI"

      - name: Run macOS Tests [ Java 19 ]
        if: matrix.os == 'macos-latest' && matrix.java-version == 19
        run: >
          ./gradlew check --stacktrace
          -PKMP_TARGETS="JVM,MACOS_ARM64,MACOS_X64,WATCHOS_ARM32,WATCHOS_ARM64,WATCHOS_DEVICE_ARM64,WATCHOS_X64,WATCHOS_SIMULATOR_ARM64"

      - name: Run Linux Tests [ Java 11 ]
        if: matrix.os == 'ubuntu-latest' && matrix.java-version == 11
        run: >
          ./gradlew check --stacktrace
          -PKMP_TARGETS="JS,JVM,WASM_JS,WASM_WASI"

      - name: Run Linux Tests [ Java 19 ]
        if: matrix.os == 'ubuntu-latest' && matrix.java-version == 19
        run: >
          ./gradlew check --stacktrace
          -PKMP_TARGETS="ANDROID,ANDROID_ARM32,ANDROID_ARM64,ANDROID_X64,ANDROID_X86,JVM,LINUX_ARM64,LINUX_X64"

      - name: Run Windows Tests [ Java 11 ]
        if: matrix.os == 'windows-latest' && matrix.java-version == 11
        run: >
          ./gradlew check --stacktrace
          -PKMP_TARGETS="JVM,JS,MINGW_X64,WASM_JS,WASM_WASI"

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: test-report-${{ matrix.os }}-java${{ matrix.java-version }}
          path: '**/build/reports/tests/**'
          retention-days: 1

  check-os-info:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu_latest
            java-version: 21
            expected-host: linux-libc
            expected-arch: aarch64
          - arch: aarch64
            distro: alpine_latest
            java-version: 21
            expected-host: linux-musl
            expected-arch: aarch64
          - arch: armv7
            distro: bullseye
            java-version: 11
            expected-host: linux-libc
            expected-arch: armv7
          - arch: ppc64le
            distro: ubuntu_latest
            java-version: 21
            expected-host: linux-libc
            expected-arch: ppc64
          - arch: ppc64le
            distro: alpine_latest
            java-version: 21
            expected-host: linux-musl
            expected-arch: ppc64
          - arch: riscv64
            distro: ubuntu_latest
            java-version: 21
            expected-host: linux-libc
            expected-arch: x86_64
          - arch: riscv64
            distro: alpine_latest
            java-version: 21
            expected-host: linux-libc
            expected-arch: riscv64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Assemble test-info.jar
        run: >
          ./gradlew :test-info:assembleFatJar
          -PKMP_TARGETS="JVM"

      - name: Check OSInfo For Host
        uses: uraimo/run-on-arch-action@v3
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          githubToken: ${{ github.token }}
          dockerRunArgs: |
            --volume "${PWD}/test-info/build/libs:/work"
            --user "$(id -u):$(id -g)"
          install: |
            case "${{ matrix.distro }}" in
              ubuntu*|jessie|stretch|buster|bullseye)
                apt-get update -q -y
                apt-get install -q -y openjdk-${{ matrix.java-version }}-jdk
                ;;
              alpine*)
                apk update
                apk add openjdk${{ matrix.java-version }}
                ;;
            esac
          run: |
            cd /work
            java -jar test-info.jar "${{ matrix.expected-host }}" "${{ matrix.expected-arch }}"

  android-check:
    strategy:
      fail-fast: false
      matrix:
        include:
          - api-level: 15
            arch: x86
          - api-level: 21
            arch: x86_64
          - api-level: 24
            arch: x86_64
          - api-level: 29
            arch: x86_64
          - api-level: 32
            arch: x86_64
          - api-level: 33
            arch: x86_64
          - api-level: 34
            arch: x86_64
          - api-level: 35
            arch: x86_64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Run Android Instrumented Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          emulator-boot-timeout: 300 # 5 minutes
          api-level: ${{ matrix.api-level }}
          arch: ${{ matrix.arch }}
          script: ./gradlew connectedCheck -PKMP_TARGETS="ANDROID,ANDROID_ARM32,ANDROID_ARM64,ANDROID_X64,ANDROID_X86,JVM"

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: test-report-android-${{ matrix.api-level }}-${{ matrix.arch }}
          path: '**/build/reports/androidTests/**'
          retention-days: 1
